### ISSUE TITLE
config[:nonblock] = true で動かしたい

### ISSUE THREAD

**Issue by ongaeshi** [matsumotory/mruby-simplehttpserver#4]
[RubyPico](https://github.com/ongaeshi/RubyPico)のWebサーバー実装に使わせてもらっております。スマホ上にRubyだけでWebサーバーを動かすことができるようになって大変便利です。

RubyPicoではmrubyをスレッドで起動(iOSはプロセスをforkできない)させており、実行中に外部から停止できるようにするためノンブロッキングソケットで実行しています。ブロッキングで実行すると[conn.recv](https://github.com/matsumotory/mruby-simplehttpserver/blob/master/mrblib/mrb_simplehttpserver.rb#L62)のC関数先でプログラムが停止してしまい、mrubyのcode_fetch_hookが呼ばれず、外部からmrubyを停止することができないためです。

mrb_simplehttpserver.rbにretryなどを加えた改造版[simplehttpserver.rb](https://github.com/ongaeshi/RubyPico/blob/master/resources/simplehttpserver.rb)が大体うまく動くようになってきたのですが、[conn.send](https://github.com/ongaeshi/RubyPico/blob/master/resources/simplehttpserver.rb#L88)のところで大きなデータ(画像など)を送信しようとすると途中までしか送信できずに画像の一部が欠けた状態で送信されてしまい困っています。以下のどちらかでうまくいくのでは考えています。

- ノンブロッキングソケットでも大きなデータを送れるようにする
- もしくは、sendのときだけブロッキングモードに変更して大きなデータを送る

sendの戻り値には送信されたバイト数が返ってくるので、全て送れなかったときは途中から再度sendすればよいのかもしれないと思い試したのですがうまく動きませんでした。何かよいアイデアがありましたらアドバイスいただけないでしょうか。

**Comment by matsumotory** [comment]
@ongaeshi バグ報告ありがとうございます。もしよろしければ、Linuxなどで同様の問題がおきるような再現コードを頂く事はできますか？

**Comment by ongaeshi** [comment]
OSXで再現できました。

https://github.com/ongaeshi/mruby-simplehttpserver-test

```
$ git clone https://github.com/ongaeshi/mruby-simplehttpserver-test.git
$ cd mruby-simplehttpserver-test
$ rake
$ ./bin/mruby sample/server.rb
```

実行すると2枚の写真が表示され、1枚目は途中までしか表示されませんが2枚目は最後まで表示されます。(1枚目は画像のサイズが大きい)

![2017-02-17 23 49 13](https://cloud.githubusercontent.com/assets/154418/23069730/ebb9440e-f56b-11e6-94d7-ab450ff15680.png)

次に https://github.com/ongaeshi/mruby-simplehttpserver-test/blob/master/sample/server.rb#L211 のコメントアウトを外して

```
$ ./bin/mruby sample/server.rb
```

だと両方表示されます。(ブロッキングモードのときはちゃんと表示される)

server.rbの上部にはカスタマイズしたmrb_simplehttpserverが貼り付けてあります。ノンブロッキング対応のために何箇所かにretryを追加したのと、:nonblockオプションが:blockオプションに変更された以外は標準のものと変わりません。

よろしくお願いします 🙇

**Comment by harasou** [comment]
@ongaeshi 

`:noblock` & `retry` の改修ですが、デーモンの待ち受け（accept）で止まらないので、loop してしまって CPU が 100% になっているようです。ここは大丈夫でしょうか？

```
$ top
 :
  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
 4709 vagrant   20   0    8976   2268   1308 R 96.7  0.5   0:04.99 mruby
```

あと、私も OSX で再現したので、Vagrant 上の Cent7 で試したところ、正常に取得できてしまいました 😓 。ご参考までに。


OSX
```
$ ./bin/mruby sample/server.rb &
$ curl -sO http://192.168.24.55:8000/image/0.jpg
$ find . -name 0.jpg -ls
13114050        8 -rw-r--r--    1 PMAC203S         staff              392202  2 18 14:45 ./0.jpg
13110004     2328 -rw-r--r--    1 PMAC203S         staff             1190203  2 18 14:02 ./sample/image/0.jpg
```
Cent7
```
$ ./bin/mruby sample/server.rb &
$ curl -sO http://192.168.24.55:8000/image/0.jpg
$ find . -name 0.jpg -ls
136106614 1164 -rw-rw-r--   1 vagrant  vagrant   1190203  2月 18 05:07 ./sample/image/0.jpg
136681062 1164 -rw-rw-r--   1 vagrant  vagrant   1190203  2月 18 05:10 ./0.jpg
```

**Comment by ongaeshi** [comment]
@harasou 再現＆指摘ありがとうございます！

> :noblock & retry の改修ですが、デーモンの待ち受け（accept）で止まらないので、loop してしまって CPU が 100% になっているようです。ここは大丈夫でしょうか？

あー駄目ですね。sleep とかして連続でアクセスしないようにする方が行儀よいと思います。

> あと、私も OSX で再現したので、Vagrant 上の Cent7 で試したところ、正常に取得できてしまいました

OSによって1回の conn.send で送れるデータの量が違うからではないかと(OSXはiOSの2倍くらい1回の転送量が大きかったです)。Cent7でも画像のサイズを大きくすると再現するかもしれません。

**Comment by harasou** [comment]
> Cent7でも画像のサイズを大きくすると再現するかもしれません。

試してみたところ、11M ぐらいのファイルでも正常に取得できました。

```
[vagrant@localhost mruby-simplehttpserver-test]$ curl -svO http://10.0.2.15:8000/image/2.jpg
* About to connect() to 10.0.2.15 port 8000 (#0)
*   Trying 10.0.2.15...
* Connected to 10.0.2.15 (10.0.2.15) port 8000 (#0)
> GET /image/2.jpg HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 10.0.2.15:8000
> Accept: */*
>
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Server: photo_server
< Date: Sat, 18 Feb 2017 07:16:06 GMT
< Content-type: image/jpeg;
< Content-length: 11117450
<
{ [data not shown]
* Closing connection 0
[vagrant@localhost mruby-simplehttpserver-test]$ find . -name 2.jpg -ls
136681066 10860 -rw-rw-r--   1 vagrant  vagrant  11117450  2月 18 07:14 ./sample/image/2.jpg
136681065 10860 -rw-rw-r--   1 vagrant  vagrant  11117450  2月 18 07:16 ./2.jpg
```

OSX 上で tcpdump みると、PhotoServer からいきなり `FIN + ACK` が送られているので、データを write した後、クライアント側の受け取りが完了する前に socket を close している気がします。


ソースを見ても、nonblock の場合は、send も nonblock になりそうですし、まずい気がするんですがどうなんだろう。
https://github.com/matsumotory/mruby-simplehttpserver/blob/master/mrblib/mrb_simplehttpserver.rb
https://github.com/matsumotory/mruby-simplehttpserver/pull/1

@matsumotory いかがでしょう？
（linux 上で再現できれば、なんとか調べれそうなのですが。。。）

**Comment by ongaeshi** [comment]
@harasou 検討違いでしたね、すいません。Linuxの方がソケットの実装が賢いのかな。

retryの処理が甘かったりと筋悪な実装をしている自覚はあるのですが、
block だと私の使っているiOSアプリでうまくいかない問題が発生して
ソースを読んだら config[:nonblock] オプションがあるのを発見し
これなら動くかもと思い改造しながら動かしていた、というのが現状です。

@harasou さんの検証のおかげで今思いついているのは

+ その1 nonblock が動くようにする
  - retry 処理がCPU100%になっている箇所を修正(sleep?)
  - nonblock のときは全てのデータを send したことを確認してから close する
+ その2 send のときは block で送る
  - recv はそのまま nonblock
  - send のときは block に変更して送信
  - ソケットは途中で nonblock から block に切り替えること可能？
+ その3 recv を外部スレッドから停止する
  - プロセスのように停止シグナルのようなものが送れればよい？
    
辺りです。

現状でもこのライブラリのおかげでiOS上にRubyだけでWebアプリを動かせるようになりました。ライブラリ自体もRubyで書かれているためiOS上での改造や検証も容易で大変助かっています、ありがとうございます :bow:

**Comment by matsumotory** [comment]
その1からその3の方針でよいのでは無いかと思います！

**Comment by ongaeshi** [comment]
その2でやってみました。sendの前に_setnonblock(true)してensureで_setnonblock(false)でうまくいきました！

https://github.com/ongaeshi/RubyPico/commit/84eb90eec7bbe0c50bdbf0c674bfdf29bf22d9fc

こちらの環境では上の修正でうまくいきましたが、割と特殊な処理を挟んでいるので
本家へのMRはしない方がよさそうかな、と判断しました。

色々とアドバイスいただきありがとうございました :bow:
