### ISSUE TITLE
Compatibility with mruby-shelf

### ISSUE THREAD

**Issue by katzer** [matsumotory/mruby-simplehttpserver#8]
@matsumotory 

I've ported the main parts of Rake to mruby - called [mruby-shelf](https://github.com/katzer/mruby-shelf) to write [mruby-yeah](https://github.com/katzer/mruby-yeah).

Therefor I've changed ruby-simplehttp to be shelf-compatible. Basically the code does only handle the socket connection and call `app.call(env)`.

Are you open to merge these (braking) changes into your repo?
https://github.com/katzer/mruby-simplehttpserver/tree/shelf

**Comment by matsumotory** [comment]
@katzer Thank you for your opinion. Yes, these patches are welcome! Please send the patches as PR.

**Comment by matsumotory** [comment]
Thanks!
